name: FloatingHotbar
main: ARTulloss\FloatingHotbar\Main
version: 1.0.2
api: 4.0.0
load: POSTWORLD
author: ARTulloss
description: Extension to make Hotbar have floating items
website: https://github.com/artulloss
depend: [Hotbar]
