<?php
/**
 * Created by PhpStorm.
 * User: Adam
 * Date: 5/17/2019
 * Time: 9:51 PM
 */
declare(strict_types=1);

namespace ARTulloss\FloatingHotbar;

use pocketmine\entity\object\ItemEntity;
use pocketmine\level\Level;
use pocketmine\nbt\tag\CompoundTag;
use pocketmine\Player;

/**
 *  _  _  __ _____ __  __  ___
 * | || |/__\_   _|  \/  \| _ \
 * | >< | \/ || | | -< /\ | v /
 * |_||_|\__/ |_| |__/_||_|_|_\
 *
 * @author ARTulloss
 * @link https://github.com/artulloss
 */

class CustomItem extends ItemEntity
{
    protected $gravity = 0;
    /**
     * CustomItem constructor.
     * @param Level $level
     * @param CompoundTag $nbt
     * @param Player $owner
     */
    public function __construct(Level $level, CompoundTag $nbt, Player $owner) {
        $this->owner = $owner->getName();
        parent::__construct($level, $nbt);
        $this->setCanSaveWithChunk(false);
    }
    /**
     * @param Player $player
     */
    public function spawnTo(Player $player): void{
        if($player->getName() === $this->owner)
            parent::spawnTo($player); // TODO: Change the autogenerated stub
    }
}